# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('desciption', models.TextField()),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ip', models.GenericIPAddressField()),
                ('author_board', models.CharField(blank=True, max_length=32)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('text_full', models.TextField()),
                ('author_ip', models.GenericIPAddressField()),
                ('author_board', models.CharField(blank=True, max_length=32)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bump_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.SmallIntegerField()),
                ('bumpable', models.BooleanField(default=True)),
                ('rateable', models.BooleanField(default=True)),
                ('closed', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'All'), (1, 'Approved'), (2, 'Hidden')], default=0)),
                ('hide_reason', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onechan.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onechan.Post')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rater',
            unique_together=set([('ip', 'post')]),
        ),
    ]
