# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onechan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'All'), (2, 'Approved'), (1, 'Hidden')], default=0),
        ),
    ]
