# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onechan', '0004_auto_20160103_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smiley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('img', models.FileField(upload_to='', verbose_name='smileys/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='text_full',
            field=models.TextField(blank=True),
        ),
    ]
