# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onechan', '0005_auto_20160113_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('img', models.FileField(upload_to='', verbose_name='homeboards/')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_board',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_board',
        ),
    ]
