# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onechan', '0006_auto_20160117_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onechan.Homeboard'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onechan.Homeboard'),
        ),
    ]
