# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onechan', '0007_auto_20160117_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onechan.Post')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([('user_ip', 'post')]),
        ),
    ]
