# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onechan', '0008_auto_20160122_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeboard',
            name='img',
            field=models.FileField(upload_to='homeboards/'),
        ),
        migrations.AlterField(
            model_name='smiley',
            name='img',
            field=models.FileField(upload_to='smileys/'),
        ),
    ]
