# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onechan', '0009_auto_20160125_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onechan.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('img', models.FileField(upload_to='reactions/')),
            ],
        ),
        migrations.AddField(
            model_name='reaction',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onechan.ReactionImage'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onechan.AnonUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reactors',
            field=models.ManyToManyField(through='onechan.Reaction', to='onechan.AnonUser'),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set([('user', 'comment')]),
        ),
    ]
