# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onechan', '0010_auto_20160225_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('uri', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=128)),
                ('rating', models.SmallIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onechan.AnonUser')),
                ('raters', models.ManyToManyField(related_name='rated_links', to='onechan.AnonUser')),
            ],
        ),
    ]
